/**
 * Site Configuration
 * Generated by Vixel SEO Platform
 */
export const siteConfig = {
  // Basic info
  name: 'smarthubb',
  title: 'SmartHubb.Se',
  description: 'Smarta hem och Home Assistant - på svenska!',
  domain: 'smarthubb.se',
  language: 'sv',
  locale: 'sv_SE',

  // Author
  defaultAuthor: '',

  // Analytics
  googleAnalyticsId: 'G-E6S0Z330L6',

  // Monetization
  adsensePublisherId: '',
  adsenseEnabled: false,
  amazonAssociateTag: '',

  // Images
  socialImage: '/og-image.png',
  favicon: '/favicon.svg',
};
